# Makefile for staging directory

CONFIG_DRM_INTEL_CDV=m
CONFIG_DRM_CDV_RELEASE=y
# CONFIG_DRM_CDV_DEBUG is not set

# fix for build system bug...
obj-$(CONFIG_STAGING)		+= staging.o

obj-$(CONFIG_DRM_INTEL_CDV)	+= cdv/
